package com.samueln.spring_boot_baseline.stock.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public record CompanyOverview(
        @JsonAlias("Symbol") String symbol,
        @JsonAlias("AssetType") String assetType,
        @JsonAlias("Name") String name,
        @JsonAlias("Description") String description,
        @JsonAlias("CIK") String cik,
        @JsonAlias("Exchange") String exchange,
        @JsonAlias("Currency") String currency,
        @JsonAlias("Country") String country,
        @JsonAlias("Sector") String sector,
        @JsonAlias("Industry") String industry,
        @JsonAlias("Address") String address,
        @JsonAlias("OfficialSite") String officialSite,
        @JsonAlias("FiscalYearEnd") String fiscalYearEnd,
        @JsonAlias("LatestQuarter") String latestQuarter,
        @JsonAlias("MarketCapitalization") String marketCapitalization,
        @JsonAlias("EBITDA") String ebitda,
        @JsonAlias("PERatio") String peRatio,
        @JsonAlias("PEGRatio") String pegRatio,
        @JsonAlias("BookValue") String bookValue,
        @JsonAlias("DividendPerShare") String dividendPerShare,
        @JsonAlias("DividendYield") String dividendYield,
        @JsonAlias("EPS") String eps,
        @JsonAlias("RevenuePerShareTTM") String revenuePerShareTTM,
        @JsonAlias("ProfitMargin") String profitMargin,
        @JsonAlias("OperatingMarginTTM") String operatingMarginTTM,
        @JsonAlias("ReturnOnAssetsTTM") String returnOnAssetsTTM,
        @JsonAlias("ReturnOnEquityTTM") String returnOnEquityTTM,
        @JsonAlias("RevenueTTM") String revenueTTM,
        @JsonAlias("GrossProfitTTM") String grossProfitTTM,
        @JsonAlias("DilutedEPSTTM") String dilutedEPSTTM,
        @JsonAlias("QuarterlyEarningsGrowthYOY") String quarterlyEarningsGrowthYOY,
        @JsonAlias("QuarterlyRevenueGrowthYOY") String quarterlyRevenueGrowthYOY,
        @JsonAlias("AnalystTargetPrice") String analystTargetPrice,
        @JsonAlias("TrailingPE") String trailingPE,
        @JsonAlias("ForwardPE") String forwardPE,
        @JsonAlias("PriceToSalesRatioTTM") String priceToSalesRatioTTM,
        @JsonAlias("PriceToBookRatio") String priceToBookRatio,
        @JsonAlias("EVToRevenue") String evToRevenue,
        @JsonAlias("EVToEBITDA") String evToEBITDA,
        @JsonAlias("Beta") String beta,
        @JsonAlias("52WeekHigh") String fiftyTwoWeekHigh,
        @JsonAlias("52WeekLow") String fiftyTwoWeekLow,
        @JsonAlias("50DayMovingAverage") String fiftyDayMovingAverage,
        @JsonAlias("200DayMovingAverage") String twoHundredDayMovingAverage,
        @JsonAlias("SharesOutstanding") String sharesOutstanding,
        @JsonAlias("DividendDate") String dividendDate,
        @JsonAlias("ExDividendDate") String exDividendDate) {
}
